
server:
    port: 8081
    error:
        include-message: always


spring:
    datasource: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: freedb_Kaiser
        url: jdbc:mysql://sql.freedb.tech:3306/freedb_classrecordapi
        password: 34MypmgYT&%Axk@
    jpa:
        hibernate:
            ddl-auto: update
            format_sql: true
        show-sql: true
        open-in-view: true
    logging:
        level:
        org.springframework.transaction.interceptor: DEBUG
